### ISSUE TITLE
是否能够正常睡眠唤醒

### ISSUE THREAD

**Issue by ripmars** [qianbinbin/hackintosh-m73-tiny#1]
cfg lock 未解锁，目前无法正常睡眠唤醒。唤醒之后屏幕黑屏

**Comment by qianbinbin** [comment]
哪个版本，Catalina还是Mojave？我是可以睡眠唤醒的就没管cfg lock
参考官方文档试试修复睡眠：https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html
解锁cfg：https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html

另外你前面两个USB口能正常连接3.0的设备吗？我的有时无法识别移动硬盘，读卡器却可以，不知道是硬盘问题还是供电问题

**Comment by ripmars** [comment]
版本：Catalina 10.15.7
睡眠时间短是可以唤醒的，超过一定时间就唤醒不了了。
参考了官方的文档，也导出了BIOS，导出txt之后，未找到cfg lock字段，无法继续往下操作。

我前面的USB口能正常识别，只是速度最高50M/S

**Comment by qianbinbin** [comment]
1. Catalina我用的不多，只试过短时间睡眠，手边也没有机器。因为网卡不行就换了Mojave，Mojave是可以睡眠一晚上的

2. 你的机器背面或者bios是这样的吗：
Serial Number | PC07S4KD
Machine Type Model | 10AXA2EJJP

3. 无法唤醒是USB设备无法唤醒，还是电源键也不行？重启后进关于本机 - 系统报告 - 日志，看看有没有有用信息

4. USB的话2.0应该都ok，可以用hackintool看一下，5Gbps是USB3，480Mbps是USB2。50M/s超过了2.0的实际峰值，但是和3.0有很大差距
